# coding: utf-8

"""
    SGLang Reranker API

    Reranking API for document relevance scoring

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rerank_client_async.api.default_api import DefaultApi


class TestDefaultApi(unittest.IsolatedAsyncioTestCase):
    """DefaultApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = DefaultApi()

    async def asyncTearDown(self) -> None:
        pass

    async def test_rerank(self) -> None:
        """Test case for rerank

        Rerank documents against a query
        """
        pass


if __name__ == '__main__':
    unittest.main()
