# coding: utf-8

"""
    SGLang Reranker API

    Reranking API for document relevance scoring

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rerank_client_sync.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_rerank(self) -> None:
        """Test case for rerank

        Rerank documents against a query
        """
        pass


if __name__ == '__main__':
    unittest.main()
