# coding: utf-8

"""
    SGLang Reranker API

    Reranking API for document relevance scoring

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rerank_client_sync.models.usage_info import UsageInfo

class TestUsageInfo(unittest.TestCase):
    """UsageInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UsageInfo:
        """Test UsageInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UsageInfo`
        """
        model = UsageInfo()
        if include_optional:
            return UsageInfo(
                prompt_tokens = 56,
                total_tokens = 56
            )
        else:
            return UsageInfo(
        )
        """

    def testUsageInfo(self):
        """Test UsageInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
